services:
  mikrocopusers.sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
        - 1433:1433
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-U",
          "sa",
          "-P",
          "YourStrong@Passw0rd",
          "-Q",
          "SELECT 1",
          "-C"
        ]
      interval: 10s
      retries: 5
      start_period: 20s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    network_mode: service:mikrocopusers.sql
    command: >
      bash -c '
        for file in ./sql-scripts/*.sql; 
        do
          echo "Executing SQL file $$file"
          until /opt/mssql-tools18/bin/sqlcmd -U sa -P YourStrong@Passw0rd -i "$$file" > /dev/null -C; do
            echo "Retry SQL execution for $$file"
            sleep 1
          done
        done
        exit 0
      '
    volumes:
      - ./:/sql-scripts
    depends_on:
      mikrocopusers.sql:
        condition: service_healthy


  mikrocopusers.api:
    image: ${DOCKER_REGISTRY-}mikrocopusersapi
    build:
      context: .
      dockerfile: MikrocopUsers.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    depends_on:
      db-init:
        condition: service_completed_successfully 